apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zqww
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0005-tenant/tkrw-pr712-0075-0005-app/devfile-sample-zqww@sha256:3b5079c2bd9e5219ca9c261dd63b6e575f9a2f01899c1f54ca911b013f00b829
        name: my-nodejs
        resources: {}
status: {}
